spring.main.web-application-type=reactive
server.port=8080
spring.data.mongodb.uri=mongodb://localhost:27017/fleamarket
spring.websocket.allowed-origins=*

jwt.secret=my-256-bit-secret-key
jwt.expiration=86400000

logging.level.org.thymeleaf=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
logging.level.org.springframework.security=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=oleksandriob705@gmail.com
spring.mail.password=yboswtweatzgtury
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template-location=true
spring.thymeleaf.cache=false

